### ISSUE TITLE
plotLifeCycle order

### ISSUE THREAD

**Issue by RobSalGo** [jonesor/compadreDB#21]
I think that the stages in the function plotLifeCycle get automatically re-ordered to alphabetical, unless they are given a number before them (which is not very sensible). This makes the reading of the lifecycle from left-to-right a bit less straight forward. It'd be great if we could let the authors choose the order in which the stages appear

**Comment by jonesor** [comment]
I'm closing this here because we are dealing with it in the Rage package where the function now lives. (see https://github.com/jonesor/Rage/issues/42#issue-384850744)
