### ISSUE TITLE
Add db type ('COMADRE' or 'COMPADRE') to version slot?

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/compadreDB#23]
Suggest adding db type to version info when the db is initially compiled, so that Rcompadre methods (e.g. `show` and `fetchDB`) know for sure which database it is and can print messages accordingly, without having to resort to 'tricks' like looking at `db$Kingdom` or other columns that may be removed by the user.

Could combine with the `$Version` element, e.g. "COMPADRE 4.0.1", but I think I'd prefer a separate element e.g.
```
$Database
$Version
$DateCreated
$Agreement
```

**Comment by jonesor** [comment]
That's an easy one. I have now implemented it within the compile code. Version is now a list with elements as you suggest producing the following:

```
> compadre$version
$Database
[1] "COMPADRE"

$Version
[1] "X.X.X"

$DateCreated
[1] "Nov_27_2018"

$Agreement
[1] "https://www.compadre-db.org/Page/UserAgreement"
```
