### ISSUE TITLE
Possible normalized database structure for com(p)adreDB

### ISSUE THREAD

**Issue by ethanwhite** [jonesor/compadreDB#8]
Thanks for the chat this morning @jonesor and @robcito. Based on our
conversation I did a little thinking about a complementary data structure to current
R specific one that is more database/language agnostic. Here are some
initial thoughts on what a normalized database structure might look like for this
data. It would require processing to make it as usable as the current structure
is within R, but would allow a broader array of computational tools to access
and use the data.

The basic structure would be three tables, one each to hold the data in
`metadata`, `mat`, and `matrixClass`. `metadata` is already a table so it could
remain as it is, but with a new `StudyID` column corresponding to the current
position within the main R object for linking to other tables. It could also be
further normalized by splitting it up based on type of information (e.g.,
splitting out a separate Taxonomy table to avoid some duplication).

`mat` would have one row for each cell occurring in a matrix and store the
StudyID, the Matrix letter, row, column, and value. E.g.,:

```
StudyID,Mat,Row,Col,Value
1,A,1,1,0.1
1,A,1,2,0.3
1,A,2,1,0.2
1,A,2,2,0.2
1,U,1,1,0.1
1,U,1,2,0.3
....
7024,C,10,10,0
```

`matrixClass` would basically be a combination of the 7024 `matrixClass` objects
into one large table. E.g.,:

```
StudyID,MatrixClassNumber,MatrixClassOrganized,MatrixClassAuthor
1,1,active,Seedling
1,2,active,Small reproductive
1,3,active,Large reproductive
...
7024,10,active,Largest adult(> 5 m)
```

I'm still just getting a feel for everything going on in the data so I'm sure
I've missed some things and I didn't fully process this mornings conversation around
the vectorized versions of this data so apologies if I'm just restating something you've
already thought of.

**Comment by ethanwhite** [comment]
Just thought I'd give this issue a quick ping. I'm going to go ahead and close our issue on this, but feel free to reopen if it gets to the point where we can add it to the retriever.

**Comment by jonesor** [comment]
Hi Ethan. We are in the process right now of moving the database to a new platform which should have a proper API to access and query the database directly. This will be operational some time in the summer I think. I'll try to remember to keep you posted.

**Comment by ethanwhite** [comment]
👍
